package org.firstinspires.ftc.teamcode;

import com.bylazar.configurables.annotations.Configurable;
import com.bylazar.telemetry.PanelsTelemetry;
import com.bylazar.telemetry.TelemetryManager;
import com.pedropathing.follower.Follower;
import com.pedropathing.geometry.BezierLine;
import com.pedropathing.geometry.Pose;
import com.pedropathing.paths.PathChain;
import com.pedropathing.util.Timer;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;

import org.firstinspires.ftc.teamcode.mechanisms.gate.DualServoGate;
import org.firstinspires.ftc.teamcode.mechanisms.gate.Gate;
import org.firstinspires.ftc.teamcode.mechanisms.intake.Intake;
import org.firstinspires.ftc.teamcode.mechanisms.intake.RollerIntake;
import org.firstinspires.ftc.teamcode.mechanisms.shooter.DualFlywheelShooter;
import org.firstinspires.ftc.teamcode.mechanisms.shooter.Shooter;
import org.firstinspires.ftc.teamcode.mechanisms.turret.MultiAxisTurret;
import org.firstinspires.ftc.teamcode.mechanisms.turret.Turret;
import org.firstinspires.ftc.teamcode.pedroPathing.Constants;

/**
 * Team 32008 -- DECODE 2025-26 -- BLUE FAR autonomous. Rewritten from scratch.
 *
 * Generated by the refract FTC suite (ftc-construct) against the team's confirmed
 * team-config.yaml.
 *
 * ============================================================================
 * WHY THIS IS A REWRITE, AND WHAT THE PREVIOUS VERSION GOT WRONG
 * ============================================================================
 * Four defects were found by reading team 19859's working DECODE auto
 * (auto/BLUE_FAR_21.java) and their FollowPathCommand against this file. Each
 * one can produce "the auto does nothing" with no error message:
 *
 *  1. NO activateAllPIDFs(). Decompiling Follower.followPath() in core-2.1.2
 *     confirms it does NOT activate the PIDFs itself. Any tuning OpMode that
 *     called deactivateAllPIDFs() leaves them off until the app restarts, so
 *     the robot accepts a path and then sits still. 19859 calls this in start()
 *     on every auto. So does this one now.
 *
 *  2. NO follower.update() DURING INIT. Pedro's localizer needs to be ticking
 *     before START so the pose is live and settled. 19859 runs it in
 *     init_loop(); this file now does too, which also makes the pose visible on
 *     Panels while the robot is being placed.
 *
 *  3. WAITING ON atTargetVelocity() WITH NO ESCAPE. The old state machine held
 *     at the shooting pose until the flywheel reached speed. If the flywheel
 *     cannot reach the target -- wrong constant, low battery, jam, bad encoder
 *     -- that state never exits and the entire 30 seconds is spent parked and
 *     spinning. 19859 avoids this by driving the whole routine on TIMERS rather
 *     than sensor predicates. Here every wait has a hard timeout and the auto
 *     always advances.
 *
 *  4. TERMINATION ON !isBusy() ALONE. 19859's FollowPathCommand finishes on
 *     "!isBusy() || isRobotStuck() || atParametricEnd()". Without the stuck
 *     check, a robot pinned against a wall keeps isBusy() true forever and the
 *     auto hangs there.
 *
 * The governing principle of this rewrite: AN AUTONOMOUS THAT SCORES NOTHING IS
 * BAD, BUT AN AUTONOMOUS THAT FREEZES IS WORSE -- it also cannot park. Every
 * state is bounded in time, and a global deadline forces the park attempt no
 * matter what else is happening.
 *
 * ============================================================================
 * PATH -- the team's 8 segments, split into 6 chains
 * ============================================================================
 * A single PathChain runs end to end without stopping, which stop-and-shoot
 * cannot use. Splitting also puts the two near-reversals on chain boundaries
 * where the robot fully stops, instead of asking the follower to swing through
 * them mid-chain (measured: corner 3->4 is 164.8 deg, corner 7->8 is 177.4 deg;
 * the two corners that stay inside a chain are the mildest at 40.6 and 68.1).
 *
 *   toShoot   seg 1        start -> shoot        then SHOOT (preload)
 *   pickup1   segs 2 + 3   shoot -> pickup1      intake running
 *   toShoot1  seg 4        pickup1 -> shoot      then SHOOT
 *   pickup2   segs 5 + 6   shoot -> pickup2      intake running
 *   toShoot2  seg 7        pickup2 -> shoot      then SHOOT
 *   park      seg 8        shoot -> park
 *
 * Turret holds one parked setpoint for the whole run, per the team's choice.
 * NOTE: MultiAxisTurret zeroes its encoder at init, so park the turret in the
 * same physical orientation before every INIT or the setpoint means something
 * different run to run.
 */
@Autonomous(name = "32008 Blue Far Auto", group = "32008")
@Configurable
public class BlueFarAuto extends OpMode {

    // ---- Field poses, from the team's supplied path (inches, Pedro frame) ----
    private static final Pose START_POSE    = new Pose(55.790,  8.210, Math.toRadians(90));
    private static final Pose SHOOT_POSE    = new Pose(66.723, 18.970, Math.toRadians(120));
    private static final Pose MID_1_POSE    = new Pose(48.906, 34.497, Math.toRadians(180));
    private static final Pose PICKUP_1_POSE = new Pose(11.004, 34.805, Math.toRadians(180));
    private static final Pose SHOOT_2_POSE  = new Pose(67.108, 19.091, Math.toRadians(120));
    private static final Pose MID_2_POSE    = new Pose(48.862, 59.883, Math.toRadians(180));
    private static final Pose PICKUP_2_POSE = new Pose(14.918, 58.551, Math.toRadians(180));
    private static final Pose SHOOT_3_POSE  = new Pose(67.119, 19.121, Math.toRadians(120));
    private static final Pose PARK_POSE     = new Pose(57.735, 26.906, Math.toRadians(120));

    // ---- Timeouts, all seconds. Every one of these exists to stop a hang. ----
    /** Longest a single path may run before the auto gives up and moves on. */
    public static double PATH_TIMEOUT = 6.0;
    /** Longest to wait for the flywheel before firing anyway. */
    public static double SPINUP_TIMEOUT = 2.5;
    /** Hard deadline: at this point the auto abandons whatever it is doing and parks. */
    public static double PARK_DEADLINE = 25.0;

    private enum State {
        DRIVE_TO_SHOOT_1, SHOOT_1,
        DRIVE_PICKUP_1,   DRIVE_TO_SHOOT_2, SHOOT_2,
        DRIVE_PICKUP_2,   DRIVE_TO_SHOOT_3, SHOOT_3,
        PARK, DONE
    }

    private Follower follower;
    private TelemetryManager panelsTelemetry;

    private final Shooter shooter = new DualFlywheelShooter();
    private final Intake  intake  = new RollerIntake();
    private final Gate    gate    = new DualServoGate();
    private final Turret  turret  = new MultiAxisTurret();

    private PathChain toShoot, pickup1, toShoot1, pickup2, toShoot2, park;

    private State state = State.DRIVE_TO_SHOOT_1;
    private final Timer stateTimer = new Timer();
    private final Timer opmodeTimer = new Timer();

    /** Set once the gates have opened for the current shot, so feed time is measured from there. */
    private boolean feeding = false;
    private final Timer feedTimer = new Timer();
    /** Last reason the state machine advanced -- surfaced on telemetry for debugging. */
    private String lastTransition = "none";

    @Override
    public void init() {
        panelsTelemetry = PanelsTelemetry.INSTANCE.getTelemetry();

        follower = Constants.createFollower(hardwareMap);
        follower.setStartingPose(START_POSE);

        shooter.init(hardwareMap);
        intake.init(hardwareMap);
        gate.init(hardwareMap);
        turret.init(hardwareMap);

        buildPaths();

        panelsTelemetry.debug("Status", "Initialized -- BLUE FAR");
        panelsTelemetry.update(telemetry);
    }

    /**
     * Keeps the localizer ticking before START. Pedro needs this to have a live,
     * settled pose the moment the match begins -- and it lets the drive team see
     * the pose on Panels while placing the robot.
     */
    @Override
    public void init_loop() {
        follower.update();
        panelsTelemetry.debug("Status", "Ready -- place robot on the LAUNCH LINE");
        panelsTelemetry.debug("X", follower.getPose().getX());
        panelsTelemetry.debug("Y", follower.getPose().getY());
        panelsTelemetry.debug("Heading (deg)", Math.toDegrees(follower.getPose().getHeading()));
        panelsTelemetry.update(telemetry);
    }

    private void buildPaths() {
        toShoot = follower.pathBuilder()
                .addPath(new BezierLine(START_POSE, SHOOT_POSE))
                .setLinearHeadingInterpolation(Math.toRadians(90), Math.toRadians(120))
                .build();

        pickup1 = follower.pathBuilder()
                .addPath(new BezierLine(SHOOT_POSE, MID_1_POSE))
                .setLinearHeadingInterpolation(Math.toRadians(120), Math.toRadians(180))
                .addPath(new BezierLine(MID_1_POSE, PICKUP_1_POSE))
                .setTangentHeadingInterpolation()
                .build();

        toShoot1 = follower.pathBuilder()
                .addPath(new BezierLine(PICKUP_1_POSE, SHOOT_2_POSE))
                .setLinearHeadingInterpolation(Math.toRadians(180), Math.toRadians(120))
                .build();

        pickup2 = follower.pathBuilder()
                .addPath(new BezierLine(SHOOT_2_POSE, MID_2_POSE))
                .setLinearHeadingInterpolation(Math.toRadians(120), Math.toRadians(180))
                .addPath(new BezierLine(MID_2_POSE, PICKUP_2_POSE))
                .setTangentHeadingInterpolation()
                .build();

        toShoot2 = follower.pathBuilder()
                .addPath(new BezierLine(PICKUP_2_POSE, SHOOT_3_POSE))
                .setLinearHeadingInterpolation(Math.toRadians(180), Math.toRadians(120))
                .build();

        park = follower.pathBuilder()
                .addPath(new BezierLine(SHOOT_3_POSE, PARK_POSE))
                .setTangentHeadingInterpolation()
                .build();
    }

    @Override
    public void start() {
        // Defect 1: followPath() does not do this, and a tuning OpMode may have
        // switched the PIDFs off. Without it the robot accepts paths and sits still.
        follower.activateAllPIDFs();

        turret.setSetpoint(RobotConstants.TURRET_PARK_YAW_DEG,
                           RobotConstants.TURRET_PARK_PITCH_PERCENT);

        // Spin up on the way to the first shot rather than after arriving.
        shooter.setTargetVelocity(RobotConstants.SHOOTER_TARGET_TICKS_PER_SEC);

        opmodeTimer.resetTimer();
        follower.followPath(toShoot, true);
        setState(State.DRIVE_TO_SHOOT_1, "start");
    }

    @Override
    public void loop() {
        follower.update();
        turret.update();

        // Global deadline. Whatever is happening, get to the park attempt with
        // enough time left to finish it -- parking is worth real points and a
        // frozen state machine cannot claim them.
        if (opmodeTimer.getElapsedTimeSeconds() > PARK_DEADLINE
                && state != State.PARK && state != State.DONE) {
            abortToPark();
        } else {
            runStateMachine();
        }

        report();
    }

    @Override
    public void stop() {
        shooter.stop();
        intake.stop();
        turret.stop();
    }

    /**
     * True once the current path is done, stuck, or has taken too long.
     *
     * Three-way like 19859's FollowPathCommand.isFinished(), plus a timeout.
     * isBusy() alone hangs forever on a robot pinned against a wall.
     */
    private boolean pathDone() {
        if (follower.isRobotStuck()) {
            lastTransition = "path ended: ROBOT STUCK";
            return true;
        }
        if (stateTimer.getElapsedTimeSeconds() > PATH_TIMEOUT) {
            lastTransition = "path ended: TIMEOUT";
            return true;
        }
        if (!follower.isBusy() || follower.atParametricEnd()) {
            lastTransition = "path ended: complete";
            return true;
        }
        return false;
    }

    private void runStateMachine() {
        switch (state) {

            case DRIVE_TO_SHOOT_1:
                if (pathDone()) {
                    beginShot(State.SHOOT_1);
                }
                break;

            case SHOOT_1:
                if (shotComplete()) {
                    intake.intake();
                    follower.followPath(pickup1, true);
                    setState(State.DRIVE_PICKUP_1, "shot 1 done");
                }
                break;

            case DRIVE_PICKUP_1:
                if (pathDone()) {
                    intake.stop();
                    follower.followPath(toShoot1, true);
                    setState(State.DRIVE_TO_SHOOT_2, "pickup 1 done");
                }
                break;

            case DRIVE_TO_SHOOT_2:
                if (pathDone()) {
                    beginShot(State.SHOOT_2);
                }
                break;

            case SHOOT_2:
                if (shotComplete()) {
                    intake.intake();
                    follower.followPath(pickup2, true);
                    setState(State.DRIVE_PICKUP_2, "shot 2 done");
                }
                break;

            case DRIVE_PICKUP_2:
                if (pathDone()) {
                    intake.stop();
                    follower.followPath(toShoot2, true);
                    setState(State.DRIVE_TO_SHOOT_3, "pickup 2 done");
                }
                break;

            case DRIVE_TO_SHOOT_3:
                if (pathDone()) {
                    beginShot(State.SHOOT_3);
                }
                break;

            case SHOOT_3:
                if (shotComplete()) {
                    shooter.stop();
                    intake.stop();
                    follower.followPath(park, true);
                    setState(State.PARK, "shot 3 done");
                }
                break;

            case PARK:
                if (pathDone()) {
                    setState(State.DONE, "parked");
                }
                break;

            case DONE:
            default:
                break;
        }
    }

    private void beginShot(State shotState) {
        feeding = false;
        setState(shotState, "arrived at shoot pose");
    }

    /**
     * Runs one volley and reports when it is finished.
     *
     * Waits for the flywheel, but ONLY up to SPINUP_TIMEOUT -- then it fires
     * regardless. A shot at slightly-low speed may miss; a shot that never
     * happens guarantees the rest of the auto never happens either.
     */
    private boolean shotComplete() {
        if (!feeding) {
            boolean atSpeed = shooter.atTargetVelocity();
            boolean waitedLongEnough = stateTimer.getElapsedTimeSeconds() > SPINUP_TIMEOUT;
            if (atSpeed || waitedLongEnough) {
                gate.open();
                feeding = true;
                feedTimer.resetTimer();
                lastTransition = atSpeed ? "fired: at speed" : "fired: SPINUP TIMEOUT";
            }
            return false;
        }

        if (feedTimer.getElapsedTimeSeconds() > RobotConstants.GATE_FEED_SECONDS) {
            gate.close();
            feeding = false;
            return true;
        }
        return false;
    }

    /** Global-deadline escape: stop everything scoring-related and run the park path. */
    private void abortToPark() {
        gate.close();
        shooter.stop();
        intake.stop();
        follower.followPath(park, true);
        setState(State.PARK, "ABORT: park deadline reached");
    }

    private void setState(State next, String why) {
        state = next;
        lastTransition = why;
        stateTimer.resetTimer();
    }

    private void report() {
        panelsTelemetry.debug("State", state);
        panelsTelemetry.debug("Last transition", lastTransition);
        panelsTelemetry.debug("State time (s)", stateTimer.getElapsedTimeSeconds());
        panelsTelemetry.debug("Auto time (s)", opmodeTimer.getElapsedTimeSeconds());
        panelsTelemetry.debug("X", follower.getPose().getX());
        panelsTelemetry.debug("Y", follower.getPose().getY());
        panelsTelemetry.debug("Heading (deg)", Math.toDegrees(follower.getPose().getHeading()));
        panelsTelemetry.debug("Follower busy", follower.isBusy());
        panelsTelemetry.debug("Robot stuck", follower.isRobotStuck());
        panelsTelemetry.debug("Shooter ticks/sec", shooter.getCurrentVelocity());
        panelsTelemetry.debug("Shooter at speed", shooter.atTargetVelocity());
        panelsTelemetry.debug("Gate open", gate.isOpen());
        panelsTelemetry.debug("Turret yaw (deg)", turret.getYawDegrees());
        panelsTelemetry.update(telemetry);
    }
}
