package org.firstinspires.ftc.teamcode;

import com.bylazar.configurables.annotations.Configurable;

/**
 * Live-tunable constants for team 32008.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * Hardware names below are the team's actual robot configuration:
 *   Control Hub   motors  lt, intake, lb, lf
 *                 servos  indicator, rg, lg, panel
 *                 digital rts
 *                 I2C     pp   (bus 0 -- see pedroPathing/Constants.java)
 *   Expansion Hub motors  ls, rs, rb, rf
 *
 * Two devices are deliberately absent from this file: the "indicator" light servo
 * and the "rts" digital input. The team asked to leave both alone, so no code
 * touches them -- an unused device left unwired is better than dead code that
 * looks maintained. Add them here if they ever get a job.
 *
 * Uses Panels' {@code @Configurable}, matching the Pedro Quickstart (see
 * pedroPathing/Tuning.java). FTC Dashboard's {@code @Config} is NOT available --
 * this project ships Panels instead.
 *
 * RULE THIS CLASS EXISTS UNDER: Panels may write the non-final fields (that is
 * what @Configurable is for). OpMode and mechanism code may only READ them.
 * Static fields outlive a single OpMode run, so a runtime write during run N
 * silently leaks into run N+1 -- which passes clean in any single test and shows
 * up later as "the robot behaved differently in match 2 for no reason". If a
 * value must change during a run, make it an instance field on the mechanism
 * that owns it.
 */
@Configurable
public class RobotConstants {

    // =====================================================================
    // HARDWARE NAMES. final on purpose: read once during init(), so there is
    // nothing for a live-tuning panel to usefully change mid-run.
    // Drivetrain motors (lf/lb/rf/rb) and the Pinpoint ("pp") are NOT here --
    // Pedro owns those, see pedroPathing/Constants.java.
    // =====================================================================
    public static final String SHOOTER_LEFT_NAME  = "ls";   // Expansion Hub
    public static final String SHOOTER_RIGHT_NAME = "rs";   // Expansion Hub
    public static final String INTAKE_NAME        = "intake";
    public static final String LEFT_GATE_NAME     = "lg";
    public static final String RIGHT_GATE_NAME    = "rg";
    /** "left turret" -- the yaw motor. Confirmed by the team. */
    public static final String TURRET_YAW_NAME    = "lt";
    /** Pitch/hood servo. 19859's autoaim calls this axis "panel" too. */
    public static final String TURRET_PITCH_NAME  = "panel";

    // -- Shooter --
    // Velocity is in ENCODER TICKS PER SECOND, not RPM -- that is what
    // DcMotorEx.setVelocity() takes and what 19859 tunes against, so there is no
    // counts-per-revolution conversion to get wrong.
    // BORROWED FROM TEAM 19859 at the team's instruction -- NOT measured on this robot.
    // Derived from 19859's own distance->velocity fit:
    //     velocity = 0.0501*d^2 + 1.4015*d + 1090.7, clipped to [1000, 2000]
    // evaluated at d = 72.1 in, the distance from this auto's shoot pose (67, 19) to
    // 19859's recorded blue goal (138, 6). All three shooting stops in this path are
    // within 0.4 in of each other, so one fixed value covers all of them.
    //
    // This transfers ONLY if 32008's flywheel diameter, gearing and compression match
    // 19859's. If shots land consistently short or long, this constant is the first
    // thing to retune -- and once retuned it is no longer a borrowed number, which is
    // the goal.
    public static double SHOOTER_TARGET_TICKS_PER_SEC = 1453.0;
    /** 19859's VELOCITY_TOR. */
    public static double SHOOTER_VELOCITY_TOLERANCE = 20.0;

    // 19859's velocity PIDF, applied to both flywheels.
    public static double SHOOTER_KP = 40.0;
    public static double SHOOTER_KI = 0.0;
    public static double SHOOTER_KD = 0.0;
    public static double SHOOTER_KF = 9.5;

    // -- Gates (two servos, opened and closed together) --
    // 19859's measured positions, borrowed at the team's instruction. Mirrored on
    // purpose: the servos face each other, so "open" is a LOWER value on the left and
    // a HIGHER value on the right. If a gate binds or drives the wrong way, these are
    // servo-horn-specific and will not transfer -- reseat the horn and remeasure.
    public static double LEFT_GATE_OPEN   = 0.41;
    public static double LEFT_GATE_CLOSE  = 0.51;
    public static double RIGHT_GATE_OPEN  = 0.57;
    public static double RIGHT_GATE_CLOSE = 0.47;
    /** Seconds the gates are held open to feed one volley. */
    public static double GATE_FEED_SECONDS = 0.6;

    // -- Intake --
    public static double INTAKE_POWER = 1.0;

    // -- Turret: yaw motor + pitch servo --
    /**
     * Encoder ticks spanning TURRET_FULL_RANGE_DEGREE. 19859's value, borrowed at the
     * team's instruction -- NOT measured on this robot.
     *
     * EVERY turret angle divides by this. If 32008's turret gearing differs at all, the
     * turret parks at the wrong angle while telemetry confidently reports the angle you
     * asked for -- a silent error, not a visible one. To measure: rotate the turret
     * through a known 180 degrees by hand and read the encoder delta.
     */
    public static double TURRET_FULL_RANGE_ENCODER = 668.0;
    public static double TURRET_FULL_RANGE_DEGREE = 180.0;

    /**
     * Parked yaw, degrees relative to the turret's position at init.
     *
     * DERIVED, NOT MEASURED. From the shoot pose (67, 19) at robot heading 120 deg to
     * 19859's recorded blue goal (138, 6):
     *     absolute bearing = atan2(6-19, 138-67) = -10.4 deg
     *     turret relative  = -10.4 - 120         = -130.4 deg
     *
     * CORRECTED ON ROBOT: the derived -130.4 parked the turret 180 degrees backwards in
     * both TeleOp and Auto, so +180 was applied: -130.4 + 180 = 49.6.
     *
     * Assumption 2 above is what broke -- the turret's zero does NOT point straight ahead
     * on this robot, it points straight back. That is a mounting/gearing fact, not a
     * tuning value, so it will hold until the turret is rebuilt.
     *
     * Still unverified: assumption 3, the SIGN. A 180 error and a sign error look
     * different -- 180 was backwards, a sign error would be mirrored left/right. If the
     * turret now points roughly at the goal but mirrored across the robot's centerline,
     * negate this instead of adjusting it.
     */
    public static double TURRET_PARK_YAW_DEG = 49.6;
    public static double TURRET_YAW_TOLERANCE_DEG = 2.0;
    public static double TURRET_HOLD_POWER = 0.3;

    /** Pitch servo travel limits, 0.0-1.0. Matches 19859's HOOD_LOWER/UPPER_LIMIT. */
    public static double PITCH_MIN = 0.0;
    public static double PITCH_MAX = 1.0;
    /**
     * Parked pitch as a percent of travel. From 19859's hood fit
     * 0.0043*d + 0.0902 at d = 72.1 in. Same borrowed-geometry caveat as the velocity.
     */
    public static double TURRET_PARK_PITCH_PERCENT = 0.40;
}
