package org.firstinspires.ftc.teamcode;

import com.acmerobotics.dashboard.config.Config;

/**
 * Live-tunable constants for team 32008.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * RULE THIS CLASS EXISTS UNDER: FTC Dashboard may write these fields (that is what
 * {@code @Config} is for). OpMode and mechanism code may only READ them. Static
 * fields outlive a single OpMode run, so a runtime write during run N silently
 * leaks into run N+1 -- which passes clean in any single test and shows up later
 * as "the robot behaved differently in match 2 for no reason". If a value must
 * change during a run, make it an instance field on the mechanism that owns it.
 */
@Config
public class RobotConstants {

    // =====================================================================
    // HARDWARE NAMES -- TODO(32008): NOT SUPPLIED, THESE ARE PLACEHOLDERS.
    // Every name below must match the robot configuration on the Driver
    // Station exactly, or init() throws and the OpMode dies on the field.
    // Check these before the first run. The drivetrain motors (lf/lb/rf/rb)
    // and the Pinpoint ("pp") are NOT here -- Pedro owns those, see
    // pedroPathing/Constants.java.
    // =====================================================================
    public static String SHOOTER_LEFT_NAME  = "shooterLeft";
    public static String SHOOTER_RIGHT_NAME = "shooterRight";
    public static String INTAKE_NAME        = "intake";
    public static String GATE_SERVO_NAME    = "gate";
    public static String TURRET_YAW_NAME    = "turretYaw";
    public static String TURRET_PITCH_NAME  = "turretPitch";

    // -- Shooter --
    /** TODO(32008): real target speed, from a shooting-distance test. */
    public static double SHOOTER_TARGET_RPM = 0.0;
    public static double SHOOTER_VELOCITY_TOLERANCE_RPM = 50.0;
    /** Encoder counts per revolution at the flywheel. TODO(32008): set for your motor. */
    public static double SHOOTER_CPR = 28.0;

    // -- Gate --
    /** TODO(32008): measured servo positions. Both 0.0 means the gate never moves. */
    public static double GATE_OPEN_POSITION   = 0.0;
    public static double GATE_CLOSED_POSITION = 0.0;
    /** Seconds the gate is held open to feed one volley. */
    public static double GATE_FEED_SECONDS = 0.6;

    // -- Intake --
    public static double INTAKE_POWER = 1.0;

    // -- Turret (parked at a fixed setpoint for this autonomous) --
    /** TODO(32008): parked setpoints, in encoder ticks. 0 = wherever it powered on. */
    public static int TURRET_PARK_YAW_TICKS   = 0;
    public static int TURRET_PARK_PITCH_TICKS = 0;
    public static double TURRET_HOLD_POWER = 0.3;
}
