package org.firstinspires.ftc.teamcode.teleop;

import com.bylazar.telemetry.PanelsTelemetry;
import com.bylazar.telemetry.TelemetryManager;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.util.Range;

import org.firstinspires.ftc.teamcode.RobotConstants;
import org.firstinspires.ftc.teamcode.mechanisms.gate.DualServoGate;
import org.firstinspires.ftc.teamcode.mechanisms.gate.Gate;
import org.firstinspires.ftc.teamcode.mechanisms.intake.Intake;
import org.firstinspires.ftc.teamcode.mechanisms.intake.RollerIntake;
import org.firstinspires.ftc.teamcode.mechanisms.shooter.DualFlywheelShooter;
import org.firstinspires.ftc.teamcode.mechanisms.shooter.Shooter;
import org.firstinspires.ftc.teamcode.mechanisms.turret.MultiAxisTurret;
import org.firstinspires.ftc.teamcode.mechanisms.turret.Turret;

/**
 * Team 32008 -- DECODE 2025-26 -- driver-controlled period.
 *
 * Generated by the refract FTC suite (ftc-construct) against the team's confirmed
 * team-config.yaml: mecanum drivetrain, raw SDK OpMode style, roller intake +
 * flywheel shooter + multi-axis turret + gate.
 *
 * Drive mixing and motor directions follow team 19859's working DECODE teleop --
 * their Drivetrain sets lf/lb REVERSE and leaves rf/rb FORWARD, which matches this
 * robot's Pedro MecanumConstants exactly, so the mixing transfers without sign
 * changes.
 *
 * ONE DELIBERATE DEVIATION FROM 19859: this normalizes the four wheel powers by
 * their largest magnitude. 19859 writes the raw sums straight to setPower(), which
 * the SDK clips at +/-1. Clipping does not scale the other three wheels to match,
 * so on a full-stick diagonal-plus-turn the mix is silently distorted and the robot
 * drifts off the commanded direction. Dividing by the max preserves the ratio.
 *
 * Hardware is NOT shared with pedroPathing/Constants.java. Pedro owns lf/lb/rf/rb
 * during autonomous; this OpMode owns them during teleop. Only one runs at a time,
 * so there is no contention -- but do not try to run a Pedro follower from here
 * without removing these direct motor handles first.
 *
 * CONTROLS (gamepad 1)
 *   left stick          translate
 *   right stick X       rotate
 *   left bumper (hold)  slow mode
 *   right trigger       intake in
 *   left trigger        intake out (clear a jam)
 *   right bumper        toggle flywheel on/off
 *   A (hold)            open gates to feed -- only feeds once flywheel is at speed
 *   dpad left/right     nudge turret yaw
 *   dpad up/down        nudge turret pitch
 *   B                   re-park turret at its stored setpoint
 */
@TeleOp(name = "32008 TeleOp", group = "32008")
public class MainTeleOp extends LinearOpMode {

    private DcMotorEx leftFront, leftBack, rightFront, rightBack;

    private final Shooter shooter = new DualFlywheelShooter();
    private final Intake intake = new RollerIntake();
    private final Gate gate = new DualServoGate();
    private final Turret turret = new MultiAxisTurret();

    private TelemetryManager panelsTelemetry;

    /** Fraction of full power while the slow-mode bumper is held. */
    private static final double SLOW_SCALE = 0.35;
    /** Degrees of turret yaw per loop while a dpad direction is held. */
    private static final double YAW_NUDGE_DEG = 0.75;
    /** Pitch travel fraction per loop while a dpad direction is held. */
    private static final double PITCH_NUDGE = 0.005;

    private boolean shooterOn = false;
    private boolean prevRightBumper = false;

    private double turretYawDeg = RobotConstants.TURRET_PARK_YAW_DEG;
    private double turretPitch = RobotConstants.TURRET_PARK_PITCH_PERCENT;

    @Override
    public void runOpMode() {
        panelsTelemetry = PanelsTelemetry.INSTANCE.getTelemetry();

        leftFront  = hardwareMap.get(DcMotorEx.class, "lf");
        leftBack   = hardwareMap.get(DcMotorEx.class, "lb");
        rightFront = hardwareMap.get(DcMotorEx.class, "rf");
        rightBack  = hardwareMap.get(DcMotorEx.class, "rb");

        // Same directions as pedroPathing/Constants.java and 19859's teleop.
        leftFront.setDirection(DcMotorSimple.Direction.REVERSE);
        leftBack.setDirection(DcMotorSimple.Direction.REVERSE);
        rightFront.setDirection(DcMotorSimple.Direction.FORWARD);
        rightBack.setDirection(DcMotorSimple.Direction.FORWARD);

        for (DcMotorEx m : new DcMotorEx[]{leftFront, leftBack, rightFront, rightBack}) {
            m.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
            m.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
        }

        shooter.init(hardwareMap);
        intake.init(hardwareMap);
        gate.init(hardwareMap);
        turret.init(hardwareMap);

        panelsTelemetry.debug("Status", "Initialized -- 32008 TeleOp");
        panelsTelemetry.update(telemetry);

        waitForStart();

        // Hold the turret at its parked setpoint from the start, so it is somewhere
        // known rather than wherever it powered on.
        turret.setSetpoint(turretYawDeg, turretPitch);

        while (opModeIsActive()) {
            drive();
            handleIntake();
            handleShooterAndGate();
            handleTurret();

            turret.update();
            report();
        }

        shooter.stop();
        intake.stop();
        turret.stop();
    }

    private void drive() {
        double y  = -gamepad1.left_stick_y;   // stick Y is inverted on the SDK
        double x  =  gamepad1.left_stick_x;
        double rx =  gamepad1.right_stick_x;

        double lf = y + x + rx;
        double lb = y - x + rx;
        double rf = y - x - rx;
        double rb = y + x - rx;

        // Normalize: preserves the ratio between wheels instead of letting the SDK
        // clip each one independently. Denominator never drops below 1, so small
        // stick inputs are not amplified.
        double denom = Math.max(1.0,
                Math.max(Math.abs(lf), Math.max(Math.abs(lb),
                        Math.max(Math.abs(rf), Math.abs(rb)))));

        double scale = gamepad1.left_bumper ? SLOW_SCALE : 1.0;

        leftFront.setPower(lf / denom * scale);
        leftBack.setPower(lb / denom * scale);
        rightFront.setPower(rf / denom * scale);
        rightBack.setPower(rb / denom * scale);
    }

    private void handleIntake() {
        if (gamepad1.right_trigger > 0.1) {
            intake.intake();
        } else if (gamepad1.left_trigger > 0.1) {
            intake.reverse();
        } else {
            intake.stop();
        }
    }

    private void handleShooterAndGate() {
        // Rising edge only -- polling the bumper directly would toggle every loop
        // it is held, which at ~50 Hz means the flywheel state is effectively random
        // by the time the driver lets go.
        boolean rightBumper = gamepad1.right_bumper;
        if (rightBumper && !prevRightBumper) {
            shooterOn = !shooterOn;
            shooter.setTargetVelocity(shooterOn ? RobotConstants.SHOOTER_TARGET_TICKS_PER_SEC : 0.0);
        }
        prevRightBumper = rightBumper;

        // Feeding before the flywheel is up to speed is how artifacts get launched
        // short. atTargetVelocity() also returns false whenever the target is 0, so
        // this cannot feed into a stopped shooter.
        if (gamepad1.a && shooter.atTargetVelocity()) {
            gate.open();
        } else {
            gate.close();
        }
    }

    private void handleTurret() {
        if (gamepad1.b) {
            turretYawDeg = RobotConstants.TURRET_PARK_YAW_DEG;
            turretPitch  = RobotConstants.TURRET_PARK_PITCH_PERCENT;
        }

        if (gamepad1.dpad_left)  turretYawDeg += YAW_NUDGE_DEG;
        if (gamepad1.dpad_right) turretYawDeg -= YAW_NUDGE_DEG;
        if (gamepad1.dpad_up)    turretPitch  += PITCH_NUDGE;
        if (gamepad1.dpad_down)  turretPitch  -= PITCH_NUDGE;

        // ponytail: fixed software limits, no homing switch. The turret encoder zeroes
        // wherever the mechanism happened to sit at init, so these bounds only protect
        // against runaway nudging, not against starting out of position. A homing
        // switch on the unused "rts" digital input would make them absolute.
        turretYawDeg = Range.clip(turretYawDeg,
                -RobotConstants.TURRET_FULL_RANGE_DEGREE,
                 RobotConstants.TURRET_FULL_RANGE_DEGREE);
        turretPitch = Range.clip(turretPitch, 0.0, 1.0);

        turret.setSetpoint(turretYawDeg, turretPitch);
    }

    private void report() {
        panelsTelemetry.debug("Shooter on", shooterOn);
        panelsTelemetry.debug("Shooter ticks/sec", shooter.getCurrentVelocity());
        panelsTelemetry.debug("Shooter at speed", shooter.atTargetVelocity());
        panelsTelemetry.debug("Gate open", gate.isOpen());
        panelsTelemetry.debug("Turret yaw cmd (deg)", turretYawDeg);
        panelsTelemetry.debug("Turret yaw actual (deg)", turret.getYawDegrees());
        panelsTelemetry.debug("Turret pitch", turretPitch);
        panelsTelemetry.update(telemetry);
    }
}
