package org.firstinspires.ftc.teamcode.mechanisms.shooter;

import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.teamcode.kernel.constants.panelConstants;
import org.firstinspires.ftc.teamcode.kernel.constants.robotConfigs;

/**
 * Two-motor flywheel {@link Shooter} for team 32008 ("ls" and "rs", both on the
 * Expansion Hub). Raw FTC SDK, matching the confirmed config's
 * {@code raw_linear_opmode} style.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * Shape follows working DECODE code from team 19859: RUN_USING_ENCODER, the left
 * motor reversed (the flywheels face each other), FLOAT rather than BRAKE at zero
 * power so a spinning flywheel is never forced to stop hard, and velocity read as
 * the MEAN of both motors rather than one.
 *
 * TODO(32008): if both flywheels spin the same way on your build, drop the reversal.
 */
public class DualFlywheelShooter implements Shooter {

    private DcMotorEx left, right;
    private double targetTicksPerSecond = 0.0;

    @Override
    public void init(HardwareMap hardwareMap) {
        left  = hardwareMap.get(DcMotorEx.class, robotConfigs.LEFT_SHOOTER);
        right = hardwareMap.get(DcMotorEx.class, robotConfigs.RIGHT_SHOOTER);

        left.setDirection(DcMotorSimple.Direction.REVERSE);

        for (DcMotorEx m : new DcMotorEx[]{left, right}) {
            m.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
            m.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);
            m.setVelocityPIDFCoefficients(panelConstants.SHOOTER_KP, panelConstants.SHOOTER_KI,
                    panelConstants.SHOOTER_KD, panelConstants.SHOOTER_KF);
        }
    }

    @Override
    public void setTargetVelocity(double ticksPerSecond) {
        targetTicksPerSecond = ticksPerSecond;
        left.setVelocity(ticksPerSecond);
        right.setVelocity(ticksPerSecond);
    }

    @Override
    public double getCurrentVelocity() {
        return (left.getVelocity() + right.getVelocity()) / 2.0;
    }

    @Override
    public boolean atTargetVelocity() {
        // A zero target is never "at speed" -- otherwise the auto would fire before
        // anyone set a real velocity, which is exactly the state while
        // SHOOTER_TARGET_TICKS_PER_SEC is still its TODO placeholder of 0.
        if (targetTicksPerSecond <= 0.0) {
            return false;
        }
        return Math.abs(getCurrentVelocity() - targetTicksPerSecond)
                <= panelConstants.VELOCITY_TOR;
    }

    @Override
    public void stop() {
        targetTicksPerSecond = 0.0;
        left.setPower(0.0);
        right.setPower(0.0);
    }
}
