package org.firstinspires.ftc.teamcode.mechanisms.shooter;

import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.teamcode.RobotConstants;

/**
 * Two-motor flywheel {@link Shooter} for team 32008, written against the raw FTC
 * SDK (the confirmed config selects {@code opmode_style: raw_linear_opmode}, so no
 * command framework is pulled in here).
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * The right motor is reversed on the assumption the two flywheels face each other.
 * TODO(32008): if both flywheels spin the same way on your build, drop that reversal.
 *
 * Velocity is measured from the LEFT motor only. Both motors are commanded to the
 * same setpoint, so a divergence between them (a slipping belt, a dead motor) will
 * NOT be caught by atTargetVelocity(). Watch the telemetry line for both.
 */
public class DualFlywheelShooter implements Shooter {

    private DcMotorEx left, right;
    private double targetRpm = 0.0;

    @Override
    public void init(HardwareMap hardwareMap) {
        left  = hardwareMap.get(DcMotorEx.class, RobotConstants.SHOOTER_LEFT_NAME);
        right = hardwareMap.get(DcMotorEx.class, RobotConstants.SHOOTER_RIGHT_NAME);

        right.setDirection(DcMotorSimple.Direction.REVERSE);

        for (DcMotorEx m : new DcMotorEx[]{left, right}) {
            m.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
            m.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
            m.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);
        }
    }

    @Override
    public void setTargetVelocity(double rpm) {
        targetRpm = rpm;
        double ticksPerSecond = rpm * RobotConstants.SHOOTER_CPR / 60.0;
        left.setVelocity(ticksPerSecond);
        right.setVelocity(ticksPerSecond);
    }

    @Override
    public double getCurrentVelocity() {
        return left.getVelocity() * 60.0 / RobotConstants.SHOOTER_CPR;
    }

    @Override
    public boolean atTargetVelocity() {
        // A zero target is never "at speed" -- otherwise the auto would fire before
        // anyone set a real RPM, which is exactly what happens while
        // RobotConstants.SHOOTER_TARGET_RPM is still its TODO placeholder of 0.
        if (targetRpm <= 0.0) {
            return false;
        }
        return Math.abs(getCurrentVelocity() - targetRpm) <= RobotConstants.SHOOTER_VELOCITY_TOLERANCE_RPM;
    }

    @Override
    public void stop() {
        targetRpm = 0.0;
        left.setPower(0.0);
        right.setPower(0.0);
    }
}
