package org.firstinspires.ftc.teamcode.mechanisms.shooter;

import com.qualcomm.robotcore.hardware.HardwareMap;

/**
 * DECODE mechanism interface: launches artifacts at a commanded speed.
 * Derived from season-extensions/decode-2025-26.yaml's {@code shooter} axis;
 * team 32008's confirmed config selects {@code flywheel}.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * Speed is in ENCODER TICKS PER SECOND throughout -- what DcMotorEx.setVelocity()
 * natively takes. Working DECODE code from team 19859 tunes in these units too, so
 * their numbers transfer directly and no counts-per-revolution conversion can be
 * gotten wrong.
 */
public interface Shooter {

    /** Acquire hardware from the hardware map. */
    void init(HardwareMap hardwareMap);

    /** Command a target flywheel speed, in ticks/sec. Pass 0 to spin down. */
    void setTargetVelocity(double ticksPerSecond);

    /** Mean measured speed across both flywheels, in ticks/sec. */
    double getCurrentVelocity();

    /** True once measured speed is within tolerance of the last commanded target. */
    boolean atTargetVelocity();

    /** Cut power immediately. */
    void stop();
}
