package org.firstinspires.ftc.teamcode.mechanisms.shooter;

import com.qualcomm.robotcore.hardware.HardwareMap;

/**
 * DECODE mechanism interface: launches artifacts at a commanded speed.
 * Derived from season-extensions/decode-2025-26.yaml's {@code shooter} axis;
 * team 32008's confirmed config selects {@code flywheel}.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * An OpMode talks to a Shooter through these methods, never through a raw
 * DcMotorEx. That is what keeps shooter-specific logic out of the OpMode.
 */
public interface Shooter {

    /** Acquire hardware from the hardware map. */
    void init(HardwareMap hardwareMap);

    /** Command a target flywheel speed, in RPM. Pass 0 to spin down. */
    void setTargetVelocity(double rpm);

    /** Current measured flywheel speed, in RPM. */
    double getCurrentVelocity();

    /** True once measured speed is within tolerance of the last commanded target. */
    boolean atTargetVelocity();

    /** Cut power immediately. */
    void stop();
}
