package org.firstinspires.ftc.teamcode.mechanisms.gate;

import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.Servo;

import org.firstinspires.ftc.teamcode.kernel.constants.RobotConfigs;
import org.firstinspires.ftc.teamcode.kernel.constants.RobotConstants;

/**
 * Two-servo {@link Gate} for team 32008 ("lg" and "rg"), opened and closed
 * together.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * Each side gets its OWN open and close position rather than sharing one pair --
 * the servos face each other, so their travel is mirrored and a shared value
 * would drive one of them the wrong way.
 *
 * TODO(32008): all four positions are 0.0 until measured, so the gates will not
 * move and nothing will feed.
 */
public class DualServoGate implements Gate {

    private Servo leftGate, rightGate;
    private boolean open = false;

    @Override
    public void init(HardwareMap hardwareMap) {
        leftGate  = hardwareMap.get(Servo.class, RobotConfigs.LEFT_GATE);
        rightGate = hardwareMap.get(Servo.class, RobotConfigs.RIGHT_GATE);
        close();
    }

    @Override
    public void open() {
        leftGate.setPosition(RobotConstants.LEFT_GATE_OPEN);
        rightGate.setPosition(RobotConstants.RIGHT_GATE_OPEN);
        open = true;
    }

    @Override
    public void close() {
        leftGate.setPosition(RobotConstants.LEFT_GATE_CLOSE);
        rightGate.setPosition(RobotConstants.RIGHT_GATE_CLOSE);
        open = false;
    }

    @Override
    public boolean isOpen() {
        return open;
    }
}
