package org.firstinspires.ftc.teamcode.mechanisms.gate;

import com.qualcomm.robotcore.hardware.HardwareMap;

/**
 * DECODE mechanism interface: holds artifacts back from the shooter and releases
 * them to feed. Derived from season-extensions/decode-2025-26.yaml's
 * {@code gate_mechanism} axis; team 32008's confirmed config selects {@code present}.
 *
 * Generated by the refract FTC suite (ftc-construct).
 */
public interface Gate {

    /** Acquire hardware from the hardware map. */
    void init(HardwareMap hardwareMap);

    /** Release artifacts into the shooter. */
    void open();

    /** Hold artifacts back. */
    void close();

    /** True if the gate was last commanded open. */
    boolean isOpen();
}
