package org.firstinspires.ftc.teamcode.mechanisms.gate;

import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.Servo;

import org.firstinspires.ftc.teamcode.RobotConstants;

/**
 * Servo-actuated {@link Gate} for team 32008.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * TODO(32008): GATE_OPEN_POSITION and GATE_CLOSED_POSITION are both 0.0 until
 * measured, so the gate will not move and nothing will feed. Set them before
 * expecting this autonomous to score.
 */
public class ServoGate implements Gate {

    private Servo servo;
    private boolean open = false;

    @Override
    public void init(HardwareMap hardwareMap) {
        servo = hardwareMap.get(Servo.class, RobotConstants.GATE_SERVO_NAME);
        close();
    }

    @Override
    public void open() {
        servo.setPosition(RobotConstants.GATE_OPEN_POSITION);
        open = true;
    }

    @Override
    public void close() {
        servo.setPosition(RobotConstants.GATE_CLOSED_POSITION);
        open = false;
    }

    @Override
    public boolean isOpen() {
        return open;
    }
}
