package org.firstinspires.ftc.teamcode.auto;

import com.bylazar.configurables.annotations.Configurable;
import com.bylazar.telemetry.PanelsTelemetry;
import com.bylazar.telemetry.TelemetryManager;
import com.pedropathing.follower.Follower;
import com.pedropathing.geometry.BezierLine;
import com.pedropathing.geometry.Pose;
import com.pedropathing.math.Vector;
import com.pedropathing.paths.PathChain;
import com.pedropathing.util.Timer;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;

import org.firstinspires.ftc.teamcode.kernel.constants.autoConstants;
import org.firstinspires.ftc.teamcode.kernel.constants.robotConstants;
import org.firstinspires.ftc.teamcode.kernel.motion.GoTo;
import org.firstinspires.ftc.teamcode.mechanisms.gate.DualServoGate;
import org.firstinspires.ftc.teamcode.mechanisms.gate.Gate;
import org.firstinspires.ftc.teamcode.mechanisms.intake.RollerIntake;
import org.firstinspires.ftc.teamcode.mechanisms.shooter.DualFlywheelShooter;
import org.firstinspires.ftc.teamcode.mechanisms.turret.AutoAim;
import org.firstinspires.ftc.teamcode.pedroPathing.Constants;

/**
 * Team 32008 -- DECODE 2025-26 -- BLUE FAR autonomous.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * Aiming is closed-loop on the live Pedro pose via {@link AutoAim}, ported from
 * 32008's own AutoAimSubsystem. It replaces the fixed autoConstants.BLUE_FAR_TURRET
 * angle this file used to command, which only pointed at the goal from 32008's own
 * shoot pose at heading 180 deg -- from this path's 120 deg the same number was
 * ~60 deg off, pointing at the RED goal. See AutoAim's class comment for the
 * field-frame derivation and the three cross-checks behind it.
 *
 * The turret tracks every loop, including while driving, so it is already on
 * target when the robot stops and only the flywheel still has to settle.
 */
@Autonomous(name = "32008 Blue Far Auto", group = "32008")
@Configurable
public class BlueFarAuto extends OpMode {

    // 32008's start POSITION, this path's own start HEADING (90 deg).
    // Their 180 deg belongs to their path; mixing it in here rotates Pedro's whole
    // field frame 90 deg from reality and the robot drives sideways/backwards.
    private static final Pose START_POSE = new Pose(
            autoConstants.BLUE_FAR_START.getX(),
            autoConstants.BLUE_FAR_START.getY(),
            Math.toRadians(90));
    private static final Pose SHOOT_POSE    = new Pose(66.723, 18.970, Math.toRadians(120));
    private static final Pose MID_1_POSE    = new Pose(48.906, 34.497, Math.toRadians(180));
    private static final Pose PICKUP_1_POSE = new Pose(11.004, 34.805, Math.toRadians(180));
    private static final Pose SHOOT_2_POSE  = new Pose(67.108, 19.091, Math.toRadians(120));
    private static final Pose MID_2_POSE    = new Pose(48.862, 59.883, Math.toRadians(180));
    private static final Pose PICKUP_2_POSE = new Pose(14.918, 58.551, Math.toRadians(180));
    private static final Pose SHOOT_3_POSE  = new Pose(67.119, 19.121, Math.toRadians(120));
    private static final Pose PARK_POSE     = new Pose(57.735, 26.906, Math.toRadians(120));

    public static double PATH_TIMEOUT = 6.0;
    public static double SPINUP_TIMEOUT = 2.5;
    public static double PARK_DEADLINE = 25.0;

    private enum State {
        DRIVE_TO_SHOOT_1, SHOOT_1,
        DRIVE_PICKUP_1,   DRIVE_TO_SHOOT_2, SHOOT_2,
        DRIVE_PICKUP_2,   DRIVE_TO_SHOOT_3, SHOOT_3,
        PARK, DONE
    }

    private Follower follower;
    private GoTo goTo;
    private TelemetryManager panelsTelemetry;

    private final DualFlywheelShooter shooter = new DualFlywheelShooter();
    private final RollerIntake intake = new RollerIntake();
    private final Gate gate = new DualServoGate();
    private final AutoAim autoAim = new AutoAim();

    private AutoAim.TurretCommand aim = new AutoAim.TurretCommand();

    private PathChain pickup1, pickup2, park;

    private State state = State.DRIVE_TO_SHOOT_1;
    private final Timer stateTimer = new Timer();
    private final Timer opmodeTimer = new Timer();
    private final Timer feedTimer = new Timer();

    private boolean feeding = false;
    private String lastTransition = "none";

    @Override
    public void init() {
        panelsTelemetry = PanelsTelemetry.INSTANCE.getTelemetry();

        follower = Constants.createFollower(hardwareMap);
        follower.setStartingPose(START_POSE);
        goTo = new GoTo(follower);

        shooter.init(hardwareMap);
        intake.init(hardwareMap);
        gate.init(hardwareMap);
        autoAim.init(hardwareMap);
        gate.close();

        buildPaths();

        panelsTelemetry.debug("Status", "Initialized -- BLUE FAR");
        panelsTelemetry.update(telemetry);
    }

    @Override
    public void init_loop() {
        follower.update();
        panelsTelemetry.debug("Status", "Ready -- park turret FORWARD, robot on LAUNCH LINE");
        panelsTelemetry.debug("X", follower.getPose().getX());
        panelsTelemetry.debug("Y", follower.getPose().getY());
        panelsTelemetry.debug("Heading (deg)", Math.toDegrees(follower.getPose().getHeading()));
        // Sanity check before every match: must read 8 / 136, NOT 136 / 136.
        // 136/136 is the RED goal and means the frame conversion got reverted.
        panelsTelemetry.debug("Blue goal X (Pedro)", AutoAim.BLUE_GOAL_X);
        panelsTelemetry.debug("Blue goal Y (Pedro)", AutoAim.BLUE_GOAL_Y);
        panelsTelemetry.update(telemetry);
    }

    private void buildPaths() {
        // toShoot, toShoot1, toShoot2 are single-segment, linear-heading legs,
        // so i removed them and used the kernel's goto API instead

        pickup1 = follower.pathBuilder()
                .addPath(new BezierLine(SHOOT_POSE, MID_1_POSE))
                .setLinearHeadingInterpolation(Math.toRadians(120), Math.toRadians(180))
                .addPath(new BezierLine(MID_1_POSE, PICKUP_1_POSE))
                .setTangentHeadingInterpolation()
                .build();

        pickup2 = follower.pathBuilder()
                .addPath(new BezierLine(SHOOT_2_POSE, MID_2_POSE))
                .setLinearHeadingInterpolation(Math.toRadians(120), Math.toRadians(180))
                .addPath(new BezierLine(MID_2_POSE, PICKUP_2_POSE))
                .setTangentHeadingInterpolation()
                .build();

        park = follower.pathBuilder()
                .addPath(new BezierLine(SHOOT_3_POSE, PARK_POSE))
                .setTangentHeadingInterpolation()
                .build();
    }

    @Override
    public void start() {
        follower.activateAllPIDFs();

        shooter.hold();

        opmodeTimer.resetTimer();
        goTo.goTo(START_POSE, SHOOT_POSE);
        setState(State.DRIVE_TO_SHOOT_1, "start");
    }

    @Override
    public void loop() {
        follower.update();
        updateAim();

        if (opmodeTimer.getElapsedTimeSeconds() > PARK_DEADLINE
                && state != State.PARK && state != State.DONE) {
            abortToPark();
        } else {
            runStateMachine();
        }

        report();
    }

    @Override
    public void stop() {
        shooter.stop();
        intake.stop();
        autoAim.stop();
    }

    /**
     * Solves and drives the turret from the live pose, every loop -- including
     * while driving, so the turret is already on target when the robot stops.
     */
    private void updateAim() {
        Pose p = follower.getPose();
        Vector v = follower.getVelocity();
        aim = autoAim.update(
                p.getX(), p.getY(), Math.toDegrees(p.getHeading()),
                v.getXComponent(), v.getYComponent(),
                // Pedro reports heading rate in RADIANS/sec; AutoAim wants degrees.
                Math.toDegrees(follower.getAngularVelocity()),
                AutoAim.BLUE_GOAL_X, AutoAim.BLUE_GOAL_Y);
    }

    private boolean pathDone() {
        if (follower.isRobotStuck()) {
            lastTransition = "path ended: ROBOT STUCK";
            return true;
        }
        if (stateTimer.getElapsedTimeSeconds() > PATH_TIMEOUT) {
            lastTransition = "path ended: TIMEOUT";
            return true;
        }
        if (!follower.isBusy() || follower.atParametricEnd()) {
            lastTransition = "path ended: complete";
            return true;
        }
        return false;
    }

    /**
     * One volley: spin the flywheel to whatever the aim solve wants for the current
     * range, wait for the turret to lock AND the flywheel to settle, then feed for
     * GATE_FEED_SECONDS. SPINUP_TIMEOUT bounds the wait so a shot that never
     * settles cannot eat the whole autonomous period.
     */
    private boolean shotComplete() {
        if (!feeding) {
            // Keep chasing the solved speed while waiting -- the range keeps moving
            // as the follower nudges the robot into its final holding position.
            if (aim.hasTarget) {
                shooter.setTargetVelocity(aim.targetVelocity);
            }

            boolean ready = aim.hasTarget && aim.isAimLocked && shooter.atTargetVelocity();
            boolean waited = stateTimer.getElapsedTimeSeconds() > SPINUP_TIMEOUT;

            if (ready || waited) {
                gate.open();
                // Distance-scaled feed power (V2's calculateIntakePower), not a flat
                // 0.9 -- over-feeding a volley jams the gates.
                intake.fire(AutoAim.intakePowerForDistance(aim.targetDist));
                feeding = true;
                feedTimer.resetTimer();
                lastTransition = ready ? "fired: locked + at speed" : "fired: SPINUP TIMEOUT";
            }
            return false;
        }

        if (feedTimer.getElapsedTimeSeconds() > robotConstants.GATE_FEED_SECONDS) {
            gate.close();
            intake.stop();
            shooter.hold();
            feeding = false;
            return true;
        }
        return false;
    }

    private void runStateMachine() {
        switch (state) {

            case DRIVE_TO_SHOOT_1:
                if (pathDone()) setState(State.SHOOT_1, "arrived: shoot 1");
                break;

            case SHOOT_1:
                if (shotComplete()) {
                    intake.intake();
                    follower.followPath(pickup1, true);
                    setState(State.DRIVE_PICKUP_1, "shot 1 done");
                }
                break;

            case DRIVE_PICKUP_1:
                if (pathDone()) {
                    intake.stop();
                    goTo.goTo(PICKUP_1_POSE, SHOOT_2_POSE);
                    setState(State.DRIVE_TO_SHOOT_2, "pickup 1 done");
                }
                break;

            case DRIVE_TO_SHOOT_2:
                if (pathDone()) setState(State.SHOOT_2, "arrived: shoot 2");
                break;

            case SHOOT_2:
                if (shotComplete()) {
                    intake.intake();
                    follower.followPath(pickup2, true);
                    setState(State.DRIVE_PICKUP_2, "shot 2 done");
                }
                break;

            case DRIVE_PICKUP_2:
                if (pathDone()) {
                    intake.stop();
                    goTo.goTo(PICKUP_2_POSE, SHOOT_3_POSE);
                    setState(State.DRIVE_TO_SHOOT_3, "pickup 2 done");
                }
                break;

            case DRIVE_TO_SHOOT_3:
                if (pathDone()) setState(State.SHOOT_3, "arrived: shoot 3");
                break;

            case SHOOT_3:
                if (shotComplete()) {
                    shooter.stop();
                    intake.stop();
                    follower.followPath(park, true);
                    setState(State.PARK, "shot 3 done");
                }
                break;

            case PARK:
                if (pathDone()) setState(State.DONE, "parked");
                break;

            case DONE:
            default:
                break;
        }
    }

    private void abortToPark() {
        gate.close();
        shooter.stop();
        intake.stop();
        feeding = false;
        follower.followPath(park, true);
        setState(State.PARK, "ABORT: park deadline reached");
    }

    private void setState(State next, String why) {
        state = next;
        lastTransition = why;
        stateTimer.resetTimer();
    }

    private void report() {
        panelsTelemetry.debug("State", state);
        panelsTelemetry.debug("Last transition", lastTransition);
        panelsTelemetry.debug("State time (s)", stateTimer.getElapsedTimeSeconds());
        panelsTelemetry.debug("Auto time (s)", opmodeTimer.getElapsedTimeSeconds());
        panelsTelemetry.debug("X", follower.getPose().getX());
        panelsTelemetry.debug("Y", follower.getPose().getY());
        panelsTelemetry.debug("Heading (deg)", Math.toDegrees(follower.getPose().getHeading()));
        panelsTelemetry.debug("Follower busy", follower.isBusy());
        panelsTelemetry.debug("Robot stuck", follower.isRobotStuck());

        panelsTelemetry.debug("Aim has target", aim.hasTarget);
        panelsTelemetry.debug("Aim LOCKED", aim.isAimLocked);
        panelsTelemetry.debug("Aim range (in)", aim.targetDist);
        panelsTelemetry.debug("Aim turret target (deg)", aim.targetTurretAngle);
        panelsTelemetry.debug("Aim turret actual (deg)", autoAim.getFilteredTurretAngle());
        panelsTelemetry.debug("Aim error (deg)", aim.aimError);
        panelsTelemetry.debug("Aim tolerance (deg)", aim.currentTolerance);
        panelsTelemetry.debug("Aim flight time (s)", aim.flightTime);
        panelsTelemetry.debug("Aim hood", aim.targetPitch);
        panelsTelemetry.debug("Aim velocity", aim.targetVelocity);
        panelsTelemetry.debug("Battery (V)", autoAim.getBatteryVoltage());

        panelsTelemetry.debug("Shooter ticks/sec", shooter.getCurrentVelocity());
        panelsTelemetry.debug("Shooter at speed", shooter.atTargetVelocity());
        panelsTelemetry.debug("Gate open", gate.isOpen());
        panelsTelemetry.update(telemetry);
    }
}
