package org.firstinspires.ftc.teamcode.pedroPathing;

import com.pedropathing.follower.Follower;
import com.pedropathing.follower.FollowerConstants;
import com.pedropathing.ftc.FollowerBuilder;
import com.pedropathing.ftc.drivetrains.MecanumConstants;
import com.pedropathing.ftc.localization.constants.PinpointConstants;
import com.pedropathing.paths.PathConstraints;
import com.qualcomm.hardware.gobilda.GoBildaPinpointDriver;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;
import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;

import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;

/**
 * Pedro Pathing configuration for FTC team 32008 (DECODE 2025-26).
 *
 * Generated by the refract FTC suite (ftc-construct) against the team's confirmed
 * team-config.yaml. See _meta.suite_generated_code in that file.
 *
 * Grounded in library-docs/pedro-pathing/{installation,localization-tuning,examples}.md
 * (fetched 2026-07-12). Every builder call below appears verbatim in those docs;
 * nothing here is recalled from memory.
 */
public class Constants {

    public static FollowerConstants followerConstants = new FollowerConstants()
            // Robot mass in KILOGRAMS, with battery installed. Supplied by team: 12.55.
            .mass(12.55)
            // Measured by the team, Zero Power Acceleration tuners.
            .forwardZeroPowerAcceleration(-21.624337823971498)
            .lateralZeroPowerAcceleration(-59.22595640999532);

    public static MecanumConstants driveConstants = new MecanumConstants()
            .leftFrontMotorName("lf")
            .leftRearMotorName("lb")
            .rightFrontMotorName("rf")
            .rightRearMotorName("rb")
            .leftFrontMotorDirection(DcMotorSimple.Direction.REVERSE)
            .leftRearMotorDirection(DcMotorSimple.Direction.REVERSE)
            .rightFrontMotorDirection(DcMotorSimple.Direction.FORWARD)
            .rightRearMotorDirection(DcMotorSimple.Direction.FORWARD)
            .xVelocity(56.1168587752145)
            .yVelocity(63.21857121985729);

    public static PinpointConstants localizerConstants = new PinpointConstants()
            .forwardPodY(-5.3150)
            .strafePodX(0.0)
            .distanceUnit(DistanceUnit.INCH)
            .hardwareMapName("pp")
            .encoderResolution(GoBildaPinpointDriver.GoBildaOdometryPods.goBILDA_4_BAR_POD)
            .forwardEncoderDirection(GoBildaPinpointDriver.EncoderDirection.FORWARD)
            .strafeEncoderDirection(GoBildaPinpointDriver.EncoderDirection.REVERSED);

    public static PathConstraints pathConstraints = new PathConstraints(0.99, 100, 1, 1);
    public static Follower createFollower(HardwareMap hardwareMap) {
        return new FollowerBuilder(followerConstants, hardwareMap)
                .mecanumDrivetrain(driveConstants)
                .pinpointLocalizer(localizerConstants)
                .pathConstraints(pathConstraints)
                .build();
    }
}
