package org.firstinspires.ftc.teamcode.mechanisms.intake;

import com.qualcomm.robotcore.hardware.HardwareMap;

/**
 * DECODE mechanism interface: brings artifacts into the robot. Derived from
 * season-extensions/decode-2025-26.yaml's {@code intake} axis; team 32008's
 * confirmed config selects {@code roller}.
 *
 * Generated by the refract FTC suite (ftc-construct).
 */
public interface Intake {

    /** Acquire hardware from the hardware map. */
    void init(HardwareMap hardwareMap);

    /** Run the intake inward (pick up artifacts). */
    void intake();

    /** Run the intake outward (clear a jam / eject). */
    void reverse();

    /** Stop the intake. */
    void stop();
}
