package org.firstinspires.ftc.teamcode.mechanisms.intake;

import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.teamcode.RobotConstants;

/**
 * Roller-type {@link Intake} for team 32008: one motor spun inward to collect,
 * outward to clear a jam. Raw FTC SDK, matching the confirmed config's
 * {@code raw_linear_opmode} style.
 *
 * Generated by the refract FTC suite (ftc-construct).
 */
public class RollerIntake implements Intake {

    private DcMotor roller;

    @Override
    public void init(HardwareMap hardwareMap) {
        roller = hardwareMap.get(DcMotor.class, RobotConstants.INTAKE_NAME);
        roller.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
    }

    @Override
    public void intake() {
        roller.setPower(RobotConstants.INTAKE_POWER);
    }

    @Override
    public void reverse() {
        roller.setPower(-RobotConstants.INTAKE_POWER);
    }

    @Override
    public void stop() {
        roller.setPower(0.0);
    }
}
