package org.firstinspires.ftc.teamcode.mechanisms.turret;

import com.bylazar.configurables.annotations.Configurable;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.Servo;
import com.qualcomm.robotcore.hardware.VoltageSensor;
import com.qualcomm.robotcore.util.Range;

import org.firstinspires.ftc.teamcode.kernel.constants.robotConfigs;
import org.firstinspires.ftc.teamcode.kernel.constants.robotConstants;

/**
 * Closed-loop pose-based turret aiming, ported from team 32008's own
 * AutoAimSubsystem (FTC-32008 V2, subsystems/AutoAimSubsystem.java).
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * WHY THIS REPLACES A FIXED TURRET ANGLE
 * --------------------------------------
 * The auto previously commanded autoConstants.BLUE_FAR_TURRET (-70 deg) and never
 * moved the turret again. That number is only correct standing on 32008's own
 * shoot pose (59, 17) at heading 180 deg. This path shoots from (66.7, 19.0) at
 * heading 120 deg, so the same -70 pointed the turret ~60 deg off -- across the
 * field, at the red goal. Solving the angle from the live pose every loop makes
 * the heading convention of the path irrelevant.
 *
 * FIELD FRAME -- THE ACTUAL BUG
 * -----------------------------
 * kernel robotConstants.BLUE_TARGET_X/Y = (136, 136) is stated in the PINPOINT
 * frame, not Pedro's. 32008's teleop converts between them at
 * tests/AASSTEST.java:59:
 *
 *     pinPoint.setPosition(new Pose2D(INCH, autoEndY, 144 - autoEndX,
 *                                     RADIANS, autoEndH - Math.PI / 2.0));
 *
 * so pinX = pedroY and pinY = 144 - pedroX. Inverting that, the BLUE goal in the
 * PEDRO frame is (144 - 136, 136) = (8, 136), and (136, 136) -- the raw kernel
 * value -- is the RED goal. Feeding the kernel numbers straight into a Pedro pose
 * aims at the wrong alliance's goal, which is exactly the reported symptom.
 *
 * Confirmed three independent ways against 32008's own verified auto constants,
 * all of which only reconcile with blue at Pedro (8, 136) and turret zero =
 * robot forward:
 *
 *   BLUE preload  from (57.166, 7.362) hdg 180: bearing 110.9 deg vs commanded
 *                 180 + (-70.5) = 109.5 deg   -> 1.4 deg apart
 *   BLUE shoot    from (59, 17) hdg 180:       bearing 113.2 deg vs commanded
 *                 180 + (-70)   = 110.0 deg   -> 3.2 deg apart
 *   RED shoot     from (85, 17) hdg 0:         bearing  66.8 deg vs commanded
 *                 0 + 70        =  70.0 deg   -> 3.2 deg apart
 *
 * The residual couple of degrees is the turret's mechanical mounting offset;
 * dial it out with YAW_OFFSET in Panels rather than by editing geometry.
 *
 * The kernel constants are NOT edited here -- the teammate's teleop consumes them
 * in the Pinpoint frame, where they are correct. The conversion belongs at the
 * Pedro-frame boundary, which is this class.
 *
 * DELIBERATE OMISSION
 * -------------------
 * V2's shoot-on-the-move branch (chassis accel filters, FORWARD/LATERAL_BRAKE_DECEL
 * brake prediction, MECHANICAL_SHOOT_DELAY release-point solve) is not ported.
 * This auto stops before every shot, so that branch would never execute, and its
 * constants were tuned against their teleop drivetrain controller rather than
 * Pedro's. The velocity flight-time lead IS kept -- it costs four lines and is
 * ~0 when stopped.
 *
 * V2 drives this loop with FTCLib's PIDFController. FTCLib is not a dependency of
 * this repo and pulling in a whole command framework for one PID class is not
 * worth it, so calculate() is inlined below with FTCLib's exact semantics --
 * including kF multiplying the SETPOINT, not the error. All four gains stay live
 * in Panels.
 */
@Configurable
public class AutoAim {

    // -- Turret velocity-loop gains, straight from V2's AutoAimSubsystem --------
    public static double TURRET_kP = 12.0;
    public static double TURRET_kI = 0.0;
    public static double TURRET_kD = 0.2;
    public static double TURRET_kF = 0.0;
    public static double TURRET_kV = 0.001593;
    public static double TURRET_kS = 0.029016;
    public static double TURRET_kA = 0.000006;
    public static double TURRET_kLinearBraking = 0.069324;
    public static double TURRET_kQuadraticFriction = 0.0;

    public static double TURRET_POWER_SIGN = 1.0;
    public static double TURRET_LATENCY = 0.012;
    public static double TURRET_MAX_POWER = 1.0;
    public static double TURRET_FILTER_ALPHA = 0.8;
    public static double TURRET_VEL_FILTER_ALPHA = 0.8;
    public static double TURRET_CMD_ACCEL_FILTER_ALPHA = 0.15;
    public static double TUNING_VOLTAGE = 13.84;

    public static double OMEGA_FILTER_ALPHA = 0.7;
    public static double HEADING_CORRECTION_ALPHA = 0.5;

    public static double TURRET_MIN_SAFE_ANGLE = -175.0;
    public static double TURRET_MAX_SAFE_ANGLE = 175.0;
    public static double TURRET_CENTER_ANGLE = 0.0;

    /**
     * Mechanical mounting offset, degrees, added to the solved bearing. The
     * cross-checks in the class comment land within ~3 deg of 32008's hand-tuned
     * angles, so 0 is the honest default -- trim it here on the field, do not
     * bend the field geometry to absorb it.
     */
    public static double YAW_OFFSET = 0.0;

    /** True zeroes the encoder at init, making 0 deg = wherever the turret sits. */
    public static boolean RESET_TURRET_ENCODER_ON_INIT = true;

    // -- Shooter flight model, from V2's Shooter.java --------------------------
    public static double AIRTIME_K = 0.003097283;
    public static double AIRTIME_G = 386.22;
    public static double TRAJECTORY_M = 1.3540990329400013;
    public static double TRAJECTORY_N = -0.4305736274862209;
    public static double TRAJECTORY_MAX_VELOCITY = 2100.0;

    /**
     * Trim between the geometric range and the range the shooter curves actually
     * want, inches. Seeded from 32008's own verified number rather than left at 0:
     *
     *   their shoot pose (59, 17) hdg 180, minus the 2.421 in shooter offset,
     *   is 128.53 in from the blue goal at Pedro (8, 136); times the 1.05 fudge
     *   already inside the solve that is 134.95 in. Their auto fires that shot at
     *   autoConstants.FAR_FIRE_DISTANCE = 126.5, so the trim is 126.5 - 134.95.
     *
     * Without this the flywheel runs ~7% hot versus their competition-verified
     * shot. This path's own shoot pose works out to the same 134.95 in, so one
     * number covers both.
     */
    public static double SHOT_DISTANCE_OFFSET = -8.45;

    /**
     * BLUE goal, PEDRO field frame, derived from the kernel's Pinpoint-frame value
     * by pedroX = 144 - pinY, pedroY = pinX. Works out to (8, 136).
     */
    public static double BLUE_GOAL_X = 144.0 - robotConstants.BLUE_TARGET_Y;
    public static double BLUE_GOAL_Y = robotConstants.BLUE_TARGET_X;

    /** RED goal in the same frame, for the mirrored auto. Works out to (136, 136). */
    public static double RED_GOAL_X = 144.0 - robotConstants.RED_TARGET_Y;
    public static double RED_GOAL_Y = robotConstants.RED_TARGET_X;

    /** What the aim solve produced this loop. */
    public static class TurretCommand {
        public boolean hasTarget = false;
        public double targetVelocity = 0.0;
        public double targetPitch = 0.0;
        public boolean isAimLocked = false;
        public double currentTolerance = 1.0;
        public double targetDist = 0.0;
        public double targetTurretAngle = 0.0;
        public double aimError = 0.0;
        public double flightTime = 0.0;
    }

    private DcMotorEx turret;
    private Servo hood;
    private HardwareMap hardwareMap;

    private double initialTurretOffset = 0.0;
    private double filteredTurretRelAngle = 0.0;
    private boolean isTurretFilterInitialized = false;
    private double lastTurretRelAngle = 0.0;
    private double filteredTurretVel = 0.0;

    private double lastTargetVel = 0.0;
    private double filteredTargetAccel = 0.0;
    private double integralError = 0.0;
    private double lastPidError = 0.0;

    private long lastTime = 0;
    private long lastVoltageReadTime = 0;
    private double currentBatteryVoltage = 12.0;

    private double filteredRobotOmega = 0.0;
    private double smoothHeading = 0.0;
    private boolean isSmoothHeadingInit = false;

    private final TurretCommand command = new TurretCommand();

    public void init(HardwareMap hardwareMap) {
        this.hardwareMap = hardwareMap;

        turret = hardwareMap.get(DcMotorEx.class, robotConfigs.TURRET);
        turret.setDirection(DcMotorSimple.Direction.REVERSE);
        if (RESET_TURRET_ENCODER_ON_INIT) {
            turret.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
        }
        // Power-controlled, NOT RUN_TO_POSITION: this class runs its own velocity
        // loop with kV/kS/kA feedforward, so the hub's positional controller must
        // stay out of the way.
        turret.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
        turret.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);

        hood = hardwareMap.get(Servo.class, robotConfigs.HOOD);
        currentBatteryVoltage = readBatteryVoltage();
    }

    /**
     * Solves and drives one aiming step. Call every loop, moving or not.
     *
     * @param robotX      drivetrain X, inches, PEDRO frame (shooter offset applied here)
     * @param robotY      drivetrain Y, inches, PEDRO frame
     * @param headingDeg  robot heading, degrees, PEDRO frame
     * @param globalVx    field-frame X velocity, in/sec (follower.getVelocity().getXComponent())
     * @param globalVy    field-frame Y velocity, in/sec
     * @param omegaDeg    heading rate, DEGREES/sec (follower.getAngularVelocity() is rad/sec)
     * @param targetX     goal X, inches, PEDRO frame -- pass {@link #BLUE_GOAL_X}
     * @param targetY     goal Y, inches, PEDRO frame -- pass {@link #BLUE_GOAL_Y}
     */
    public TurretCommand update(double robotX, double robotY, double headingDeg,
                                double globalVx, double globalVy, double omegaDeg,
                                double targetX, double targetY) {

        long nowVolts = System.nanoTime();
        if (nowVolts - lastVoltageReadTime > 250_000_000L) {
            currentBatteryVoltage = readBatteryVoltage();
            lastVoltageReadTime = nowVolts;
        }

        long nowNanos = System.nanoTime();
        double dt = lastTime == 0 ? 0.0001 : (nowNanos - lastTime) / 1e9;
        lastTime = nowNanos;

        updateTurretFilters(dt);
        updateHeadingFilter(headingDeg, omegaDeg, dt);

        double headingRad = Math.toRadians(smoothHeading);
        double cosH = Math.cos(headingRad);
        double sinH = Math.sin(headingRad);

        // The shooter does not sit over the center of rotation. V2 applies this at
        // every call site; doing it here means it cannot be forgotten.
        double shooterX = robotX + cosH * robotConstants.SHOOTER_DRIVETRAIN_OFFSET;
        double shooterY = robotY + sinH * robotConstants.SHOOTER_DRIVETRAIN_OFFSET;

        double currentDist = Math.hypot(targetX - shooterX, targetY - shooterY) * 1.05;
        double flightTime = calculateAirtime(currentDist);

        // Lead the shot by however far the robot drifts during flight. ~0 when stopped.
        double futureX = shooterX + globalVx * flightTime;
        double futureY = shooterY + globalVy * flightTime;

        double dxF = targetX - futureX;
        double dyF = targetY - futureY;
        double dist = Math.hypot(dxF, dyF) * 1.05;
        if (dist < 0.1) {
            turret.setPower(0.0);
            command.hasTarget = false;
            command.isAimLocked = false;
            return command;
        }

        double shotDist = Math.max(0.0, dist + SHOT_DISTANCE_OFFSET);

        command.hasTarget = true;
        command.targetDist = dist;
        command.flightTime = flightTime;
        command.targetVelocity = robotConstants.velocityForDistance(shotDist);
        command.targetPitch = Range.clip(robotConstants.hoodPercentForDistance(shotDist),
                robotConstants.SHOOTER_MIN_HOOD_PERCENT,
                robotConstants.SHOOTER_MAX_HOOD_PERCENT);
        command.currentTolerance = toleranceForDistance(dist);

        // Turret must counter-rotate as the robot sweeps past the goal, not just
        // as it spins in place.
        double dx = targetX - shooterX;
        double dy = targetY - shooterY;
        double distSq = dx * dx + dy * dy;
        double translationalOmegaDeg = 0.0;
        if (distSq > 0.001) {
            translationalOmegaDeg = Math.toDegrees((-dx * globalVy + dy * globalVx) / distSq);
        }

        double targetAbsAngle = Math.toDegrees(Math.atan2(dyF, dxF))
                + YAW_OFFSET
                + translationalOmegaDeg * TURRET_LATENCY;
        double currentAbsAngle = smoothHeading + filteredTurretRelAngle;
        double error = normalizeDeg(targetAbsAngle - currentAbsAngle);
        double targetRelAngle = filteredTurretRelAngle + error;

        command.targetTurretAngle = targetRelAngle;
        command.aimError = error;

        if (targetRelAngle < TURRET_MIN_SAFE_ANGLE || targetRelAngle > TURRET_MAX_SAFE_ANGLE) {
            // Would wrap the turret past its wiring limit. Recenter and report no
            // target so nothing downstream fires.
            command.hasTarget = false;
            command.isAimLocked = false;
            command.targetTurretAngle = TURRET_CENTER_ANGLE;
            driveTurretToAngle(filteredTurretRelAngle, TURRET_CENTER_ANGLE, -filteredRobotOmega, dt);
            return command;
        }

        command.isAimLocked = Math.abs(error) <= command.currentTolerance;

        // Aim past the current angle by however far the turret coasts, but only
        // when it is already travelling the wrong way.
        double predictedRelAngle = filteredTurretRelAngle;
        double brakingDist = TURRET_kLinearBraking * Math.abs(filteredTurretVel)
                + TURRET_kQuadraticFriction * filteredTurretVel * filteredTurretVel;
        if (Math.signum(error) != Math.signum(filteredTurretVel)) {
            predictedRelAngle += Math.signum(filteredTurretVel) * brakingDist;
        }

        driveTurretToAngle(predictedRelAngle, targetRelAngle,
                -filteredRobotOmega + translationalOmegaDeg, dt);
        setPitchServo(command.targetPitch);
        return command;
    }

    /**
     * Feed power for a shot at {@code distanceInches}, V2's calculateIntakePower.
     * Deliberately NOT a fixed 0.9: at the far-shot distance of 126.5 in this
     * returns ~0.70, and over-feeding a volley jams the gates.
     */
    public static double intakePowerForDistance(double distanceInches) {
        double p = -0.00003111962 * distanceInches * distanceInches
                + 0.001319851 * distanceInches
                + 1.110636;
        return Range.clip(p * 0.9, 0.35, 1.0);
    }

    public double getTurretAngle() {
        return getTurretRelativeAngle();
    }

    public double getFilteredTurretAngle() {
        return filteredTurretRelAngle;
    }

    public double getSmoothHeading() {
        return smoothHeading;
    }

    public double getBatteryVoltage() {
        return currentBatteryVoltage;
    }

    /** Parks the turret at its zero and holds, for the drive to the next shot. */
    public void center(double dt) {
        driveTurretToAngle(filteredTurretRelAngle, TURRET_CENTER_ANGLE, 0.0, dt);
    }

    public void stop() {
        turret.setPower(0.0);
        isTurretFilterInitialized = false;
        isSmoothHeadingInit = false;
        lastTime = 0;
        integralError = 0.0;
    }

    // -- internals -------------------------------------------------------------

    private double getTurretRelativeAngle() {
        return turret.getCurrentPosition() / robotConstants.TURRET_FULL_RANGE_ENCODER
                * robotConstants.TURRET_FULL_RANGE_DEGREE + initialTurretOffset;
    }

    private void setPitchServo(double targetPitch) {
        double clamped = Range.clip(targetPitch,
                robotConstants.SHOOTER_MIN_HOOD_PERCENT,
                robotConstants.SHOOTER_MAX_HOOD_PERCENT);
        hood.setPosition(clamped
                * (robotConstants.HOOD_UPPER_LIMIT - robotConstants.HOOD_LOWER_LIMIT)
                + robotConstants.HOOD_LOWER_LIMIT);
    }

    private void updateTurretFilters(double dt) {
        double raw = getTurretRelativeAngle();
        if (!isTurretFilterInitialized) {
            filteredTurretRelAngle = raw;
            lastTurretRelAngle = raw;
            filteredTurretVel = 0.0;
            lastTargetVel = 0.0;
            filteredTargetAccel = 0.0;
            isTurretFilterInitialized = true;
        } else {
            filteredTurretRelAngle = TURRET_FILTER_ALPHA * raw
                    + (1.0 - TURRET_FILTER_ALPHA) * filteredTurretRelAngle;
            if (dt > 0.0001) {
                double rawVel = (raw - lastTurretRelAngle) / dt;
                filteredTurretVel = TURRET_VEL_FILTER_ALPHA * rawVel
                        + (1.0 - TURRET_VEL_FILTER_ALPHA) * filteredTurretVel;
            }
        }
        lastTurretRelAngle = raw;
    }

    private void updateHeadingFilter(double headingDeg, double omegaDeg, double dt) {
        if (!isSmoothHeadingInit) {
            smoothHeading = headingDeg;
            filteredRobotOmega = omegaDeg;
            isSmoothHeadingInit = true;
            return;
        }
        filteredRobotOmega += OMEGA_FILTER_ALPHA * (omegaDeg - filteredRobotOmega);
        smoothHeading += filteredRobotOmega * dt;
        smoothHeading = normalizeDeg(smoothHeading
                + HEADING_CORRECTION_ALPHA * normalizeDeg(headingDeg - smoothHeading));
    }

    /** V2's tolerance ramp: loose up close, 5 deg past 90 in. */
    private double toleranceForDistance(double dist) {
        if (dist <= 20.0) return 30.0;
        if (dist >= 90.0) return 5.0;
        return 30.0 + (5.0 - 30.0) / (90.0 - 20.0) * (dist - 20.0);
    }

    private void driveTurretToAngle(double currentAngle, double targetAngle,
                                    double feedforwardVel, double dt) {
        targetAngle = Range.clip(targetAngle,
                -robotConstants.TURRET_FULL_RANGE_DEGREE,
                robotConstants.TURRET_FULL_RANGE_DEGREE);

        // FTCLib PIDFController.calculate(measured, setpoint), inlined. Note kF
        // multiplies the SETPOINT, which is FTCLib's convention, not the error.
        double pidError = targetAngle - currentAngle;
        double errorVelocity = dt > 0.0001 ? (pidError - lastPidError) / dt : 0.0;
        integralError += dt * pidError;
        lastPidError = pidError;
        double pidOutputVel = TURRET_kP * pidError
                + TURRET_kI * integralError
                + TURRET_kD * errorVelocity
                + TURRET_kF * targetAngle;

        double finalTargetVel = pidOutputVel + feedforwardVel;

        double rawTargetAccel = dt > 0.0001 ? (finalTargetVel - lastTargetVel) / dt : 0.0;
        lastTargetVel = finalTargetVel;
        filteredTargetAccel = TURRET_CMD_ACCEL_FILTER_ALPHA * rawTargetAccel
                + (1.0 - TURRET_CMD_ACCEL_FILTER_ALPHA) * filteredTargetAccel;

        double ksSign = Math.abs(finalTargetVel) > 0.5 ? Math.signum(finalTargetVel) : 0.0;
        double power = filteredTargetAccel * TURRET_kA
                + finalTargetVel * TURRET_kV
                + ksSign * TURRET_kS;

        // Same commanded angle must take the same power at 11 V as at 13.84 V.
        power *= TUNING_VOLTAGE / currentBatteryVoltage;
        turret.setPower(Range.clip(TURRET_POWER_SIGN * power, -TURRET_MAX_POWER, TURRET_MAX_POWER));
    }

    private double readBatteryVoltage() {
        double max = 0.0;
        for (VoltageSensor sensor : hardwareMap.voltageSensor) {
            double v = sensor.getVoltage();
            if (v > max) max = v;
        }
        return Math.max(8.0, max > 0.0 ? max : TUNING_VOLTAGE);
    }

    private static double normalizeDeg(double angle) {
        while (angle > 180.0) angle -= 360.0;
        while (angle < -180.0) angle += 360.0;
        return angle;
    }

    // -- flight-time model, from V2's Shooter.java -----------------------------

    private static double surfaceZ(double x, double y, double k, double g, double m, double n) {
        return ((k * x) * (k * x) / g) * Math.sin(2 * (m * y + n));
    }

    private static double zOfT(double t, double k, double g, double m, double n) {
        return surfaceZ(TRAJECTORY_MAX_VELOCITY * t, t, k, g, m, n);
    }

    private static double solveForT(double targetZ, double k, double g, double m, double n) {
        double lo = Math.max(0, -n / m);
        double hi = 0.8;
        while (zOfT(hi, k, g, m, n) < targetZ && hi < 1.0) {
            hi += 0.01;
        }
        for (int i = 0; i < 80; i++) {
            double mid = 0.5 * (lo + hi);
            if (zOfT(mid, k, g, m, n) < targetZ) {
                lo = mid;
            } else {
                hi = mid;
            }
        }
        return 0.5 * (lo + hi);
    }

    public static double calculateAirtime(double rangeInches) {
        double t = solveForT(rangeInches, AIRTIME_K, AIRTIME_G, TRAJECTORY_M, TRAJECTORY_N);
        double velocity = TRAJECTORY_MAX_VELOCITY * t;
        double launchAngle = TRAJECTORY_M * t + TRAJECTORY_N;
        return (2 * AIRTIME_K * velocity * Math.sin(launchAngle)) / AIRTIME_G;
    }
}
