package org.firstinspires.ftc.teamcode.mechanisms.turret;

import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.Servo;
import com.qualcomm.robotcore.util.Range;

import org.firstinspires.ftc.teamcode.kernel.constants.robotConfigs;
import org.firstinspires.ftc.teamcode.kernel.constants.robotConstants;

/**
 * Two-axis {@link Turret} for team 32008: a yaw MOTOR ("lt") and a pitch SERVO
 * ("panel"). Same physical arrangement as team 19859's turret + hood.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * Yaw runs in RUN_TO_POSITION. That is sufficient for this autonomous, where the
 * turret holds ONE parked angle the whole match.
 *
 * ponytail: RUN_TO_POSITION is the ceiling here -- it cannot track a moving target
 * well, because it has no velocity feedforward and no latency compensation. The
 * upgrade path, when you want auto-aim, is 19859's AutoAimSubsystem approach:
 * RUN_WITHOUT_ENCODER plus a kV/kS/kA feedforward, battery-voltage scaling
 * (power *= tuningVoltage / currentVoltage), and a flight-time lead on the target
 * position. Do not attempt shoot-on-the-move on top of RUN_TO_POSITION.
 *
 * Yaw is measured RELATIVE TO THE INIT POSITION -- the encoder is zeroed in init().
 * Park the turret by hand in a known orientation before pressing INIT.
 */
public class MultiAxisTurret implements Turret {

    private DcMotorEx yaw;
    private Servo pitch;
    private double yawTargetDeg = 0.0;

    @Override
    public void init(HardwareMap hardwareMap) {
        yaw = hardwareMap.get(DcMotorEx.class, robotConfigs.TURRET);
        yaw.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
        yaw.setTargetPosition(0);
        yaw.setMode(DcMotor.RunMode.RUN_TO_POSITION);
        yaw.setPower(robotConstants.TURRET_HOLD_POWER);
        yaw.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);

        pitch = hardwareMap.get(Servo.class, robotConfigs.HOOD);
    }

    @Override
    public void setSetpoint(double yawDegrees, double pitchPercent) {
        yawTargetDeg = yawDegrees;
        yaw.setTargetPosition((int) Math.round(degreesToTicks(yawDegrees)));
        yaw.setPower(robotConstants.TURRET_HOLD_POWER);

        double clamped = Range.clip(pitchPercent, 0.0, 1.0);
        pitch.setPosition(robotConstants.HOOD_LOWER_LIMIT
                + clamped * (robotConstants.HOOD_UPPER_LIMIT - robotConstants.HOOD_LOWER_LIMIT));
    }

    @Override
    public void update() {
        // RUN_TO_POSITION is serviced by the hub's own controller; nothing to do
        // per-loop. Present so a future closed-loop yaw controller (see the class
        // comment) can be dropped in without changing any caller.
    }

    @Override
    public double getYawDegrees() {
        return ticksToDegrees(yaw.getCurrentPosition());
    }

    @Override
    public boolean atSetpoint() {
        return Math.abs(getYawDegrees() - yawTargetDeg) <= robotConstants.TURRET_YAW_TOLERANCE_DEG;
    }

    @Override
    public void stop() {
        yaw.setPower(0.0);
    }

    private double degreesToTicks(double degrees) {
        return degrees / robotConstants.TURRET_FULL_RANGE_DEGREE
                * robotConstants.TURRET_FULL_RANGE_ENCODER;
    }

    private double ticksToDegrees(double ticks) {
        return ticks / robotConstants.TURRET_FULL_RANGE_ENCODER
                * robotConstants.TURRET_FULL_RANGE_DEGREE;
    }
}
