package org.firstinspires.ftc.teamcode.mechanisms.turret;

import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.teamcode.RobotConstants;

/**
 * Two-axis (yaw + pitch) {@link Turret} for team 32008, run in RUN_TO_POSITION.
 *
 * Generated by the refract FTC suite (ftc-construct).
 *
 * TODO(32008): DEVICE TYPES ARE UNVERIFIED. Both axes are assumed to be encoder
 * motors because no device information was supplied. If either axis is a servo,
 * this class must be rewritten for that axis -- it will not merely mis-aim, it
 * will throw on init(). Confirm against the robot configuration first.
 *
 * Encoders are zeroed at init, so every setpoint is relative to wherever the
 * turret was physically sitting when the OpMode was initialized. Park the turret
 * by hand in a known position before pressing INIT, or add a limit switch.
 */
public class MultiAxisTurret implements Turret {

    private DcMotorEx yaw, pitch;
    private int yawTarget = 0, pitchTarget = 0;

    @Override
    public void init(HardwareMap hardwareMap) {
        yaw   = hardwareMap.get(DcMotorEx.class, RobotConstants.TURRET_YAW_NAME);
        pitch = hardwareMap.get(DcMotorEx.class, RobotConstants.TURRET_PITCH_NAME);

        for (DcMotorEx m : new DcMotorEx[]{yaw, pitch}) {
            m.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
            m.setTargetPosition(0);
            m.setMode(DcMotor.RunMode.RUN_TO_POSITION);
            m.setPower(RobotConstants.TURRET_HOLD_POWER);
            m.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        }
    }

    @Override
    public void setSetpoint(int yawTicks, int pitchTicks) {
        yawTarget = yawTicks;
        pitchTarget = pitchTicks;
        yaw.setTargetPosition(yawTarget);
        pitch.setTargetPosition(pitchTarget);
        yaw.setPower(RobotConstants.TURRET_HOLD_POWER);
        pitch.setPower(RobotConstants.TURRET_HOLD_POWER);
    }

    @Override
    public boolean atSetpoint() {
        return !yaw.isBusy() && !pitch.isBusy();
    }

    @Override
    public void stop() {
        yaw.setPower(0.0);
        pitch.setPower(0.0);
    }
}
