package org.firstinspires.ftc.teamcode.mechanisms.turret;

import com.qualcomm.robotcore.hardware.HardwareMap;

/**
 * DECODE mechanism interface: aims the shooter independently of drivetrain heading.
 * Derived from season-extensions/decode-2025-26.yaml's {@code turret} axis; team
 * 32008's confirmed config selects {@code multi_axis} -- a yaw motor plus a pitch
 * ("panel") servo.
 *
 * That season file also machine-enforces "a turret requires a shooter" -- this
 * interface only makes sense alongside
 * {@link org.firstinspires.ftc.teamcode.mechanisms.shooter.Shooter}.
 *
 * Generated by the refract FTC suite (ftc-construct).
 */
public interface Turret {

    /** Acquire hardware from the hardware map. */
    void init(HardwareMap hardwareMap);

    /**
     * Command both axes.
     *
     * @param yawDegrees   yaw angle, relative to wherever the turret sat at init
     * @param pitchPercent pitch as a fraction of travel, 0.0-1.0, mapped between
     *                     robotConstants.HOOD_LOWER_LIMIT and HOOD_UPPER_LIMIT
     */
    void setSetpoint(double yawDegrees, double pitchPercent);

    /** Must be called every loop: the yaw axis is closed-loop and needs servicing. */
    void update();

    /** Current yaw angle in degrees, relative to the init position. */
    double getYawDegrees();

    /** True once yaw is within tolerance of the commanded angle. */
    boolean atSetpoint();

    /** Cut power to the yaw axis. */
    void stop();
}
