package org.firstinspires.ftc.teamcode.mechanisms.turret;

import com.qualcomm.robotcore.hardware.HardwareMap;

/**
 * DECODE mechanism interface: aims the shooter independently of drivetrain heading.
 * Derived from season-extensions/decode-2025-26.yaml's {@code turret} axis; team
 * 32008's confirmed config selects {@code multi_axis} (yaw + pitch).
 *
 * That season file also machine-enforces "a turret requires a shooter" -- this
 * interface only makes sense alongside {@link org.firstinspires.ftc.teamcode.mechanisms.shooter.Shooter}.
 *
 * Generated by the refract FTC suite (ftc-construct).
 */
public interface Turret {

    /** Acquire hardware from the hardware map. */
    void init(HardwareMap hardwareMap);

    /** Command both axes to a setpoint, in encoder ticks. */
    void setSetpoint(int yawTicks, int pitchTicks);

    /** True once both axes have reached the commanded setpoint. */
    boolean atSetpoint();

    /** Cut power to both axes. */
    void stop();
}
